In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/convolve-epoch1/sample_submission.csv
/kaggle/input/convolve-epoch1/train.json
/kaggle/input/convolve-epoch1/test.csv

In [2]:
data_path = "/kaggle/input/convolve-epoch1/train.json"
ser = pd.read_json(data_path,typ="series")
ser.to_frame('count')
df = pd.DataFrame({'count':ser})
df

                                                       count
 1117838570 2005.06.03 R02-M1-N0-C:J12-U11 2005...    normal
 1117838570 2005.06.03 R02-M1-N0-C:J12-U11 2005...    normal
 1117838570 2005.06.03 R02-M1-N0-C:J12-U11 2005...    normal
 1117838570 2005.06.03 R02-M1-N0-C:J12-U11 2005...    normal
 1117838570 2005.06.03 R02-M1-N0-C:J12-U11 2005...    normal
...                                                      ...
1118545530 2005.06.11 R30-M0-N9-C:J16-U01 2005-...  abnormal
1118545530 2005.06.11 R30-M0-N9-C:J16-U01 2005-...  abnormal
1118545530 2005.06.11 R30-M0-N9-C:J16-U01 2005-...  abnormal
1118545530 2005.06.11 R30-M0-N9-C:J16-U01 2005-...  abnormal
1118545530 2005.06.11 R30-M0-N9-C:J16-U01 2005-...  abnormal

[4152659 rows x 1 columns]

In [3]:
from sklearn.preprocessing import LabelEncoder
ohe = LabelEncoder()
df['count'] = ohe.fit_transform(df['count'])

In [4]:
df

                                                    count
 1117838570 2005.06.03 R02-M1-N0-C:J12-U11 2005...      1
 1117838570 2005.06.03 R02-M1-N0-C:J12-U11 2005...      1
 1117838570 2005.06.03 R02-M1-N0-C:J12-U11 2005...      1
 1117838570 2005.06.03 R02-M1-N0-C:J12-U11 2005...      1
 1117838570 2005.06.03 R02-M1-N0-C:J12-U11 2005...      1
...                                                   ...
1118545530 2005.06.11 R30-M0-N9-C:J16-U01 2005-...      0
1118545530 2005.06.11 R30-M0-N9-C:J16-U01 2005-...      0
1118545530 2005.06.11 R30-M0-N9-C:J16-U01 2005-...      0
1118545530 2005.06.11 R30-M0-N9-C:J16-U01 2005-...      0
1118545530 2005.06.11 R30-M0-N9-C:J16-U01 2005-...      0

[4152659 rows x 1 columns]

In [5]:
df.astype('str')

                                                   count
 1117838570 2005.06.03 R02-M1-N0-C:J12-U11 2005...     1
 1117838570 2005.06.03 R02-M1-N0-C:J12-U11 2005...     1
 1117838570 2005.06.03 R02-M1-N0-C:J12-U11 2005...     1
 1117838570 2005.06.03 R02-M1-N0-C:J12-U11 2005...     1
 1117838570 2005.06.03 R02-M1-N0-C:J12-U11 2005...     1
...                                                  ...
1118545530 2005.06.11 R30-M0-N9-C:J16-U01 2005-...     0
1118545530 2005.06.11 R30-M0-N9-C:J16-U01 2005-...     0
1118545530 2005.06.11 R30-M0-N9-C:J16-U01 2005-...     0
1118545530 2005.06.11 R30-M0-N9-C:J16-U01 2005-...     0
1118545530 2005.06.11 R30-M0-N9-C:J16-U01 2005-...     0

[4152659 rows x 1 columns]

In [6]:
df['count'][0]

1

In [7]:
x = []
for i in range(4152659):
    if(df['count'][i]==1):
        x.append(1)    
    else:
        x.append(0)

In [8]:
ded = pd.Series(x,name='Label')
ok = pd.DataFrame(ded)

In [9]:
ok

         Label
0            1
1            1
2            1
3            1
4            1
...        ...
4152654      0
4152655      0
4152656      0
4152657      0
4152658      0

[4152659 rows x 1 columns]

In [10]:
ok['Label'].value_counts()

1    4082967
0      69692
Name: Label, dtype: int64

In [11]:
import json
x = []
with open("/kaggle/input/convolve-epoch1/train.json","r") as file:
    jsonData = json.load(file)
    for i in jsonData:
        x.append(i)

In [12]:
s = pd.Series(x,name='Log')
st =s.to_frame()

In [13]:
newdf = pd.concat([st,ok],axis=1)

In [14]:
newdf

                                                       Log  Label
0         1117838570 2005.06.03 R02-M1-N0-C:J12-U11 200...      1
1         1117838570 2005.06.03 R02-M1-N0-C:J12-U11 200...      1
2         1117838570 2005.06.03 R02-M1-N0-C:J12-U11 200...      1
3         1117838570 2005.06.03 R02-M1-N0-C:J12-U11 200...      1
4         1117838570 2005.06.03 R02-M1-N0-C:J12-U11 200...      1
...                                                    ...    ...
4152654  1118545530 2005.06.11 R30-M0-N9-C:J16-U01 2005...      0
4152655  1118545530 2005.06.11 R30-M0-N9-C:J16-U01 2005...      0
4152656  1118545530 2005.06.11 R30-M0-N9-C:J16-U01 2005...      0
4152657  1118545530 2005.06.11 R30-M0-N9-C:J16-U01 2005...      0
4152658  1118545530 2005.06.11 R30-M0-N9-C:J16-U01 2005...      0

[4152659 rows x 2 columns]

In [15]:
newdf.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4152659 entries, 0 to 4152658
Data columns (total 2 columns):
 #   Column  Dtype
---  ------  -----
 0   Log     object
 1   Label   int64
dtypes: int64(1), object(1)
memory usage: 63.4+ MB

In [16]:
backup=newdf.copy()

In [17]:
newdf["c_or_i"] = newdf["Log"].str.split().str[-1]

In [18]:
newdf=newdf.replace('interrupt','50')

In [19]:
newdf['New']=newdf.c_or_i.apply(lambda x: np.where(x.isdigit(),x,'1'))

In [20]:
newdf['New'].value_counts()

1                               4006930
50                                71061
2005                              11508
0000000000000000000000000000      11116
3                                  6661
                                 ...
01298818                              1
01299008                              1
06442508                              1
06442518                              1
01200588                              1
Name: New, Length: 1339, dtype: int64

In [21]:
newdf['New']=newdf['New'].astype(int)

In [22]:
newdf['New'][newdf['New'] > 51] = 1

/opt/conda/lib/python3.7/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

In [23]:
newdf['New'][newdf['New'] < 50] = 1

/opt/conda/lib/python3.7/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

In [24]:
newdf['New'][newdf['New'] == 50] = 0

/opt/conda/lib/python3.7/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

In [25]:
newdf=newdf.drop('c_or_i',axis='columns')

In [26]:
newdf['err_id']=newdf['Log'].str.split().str.get(0).astype(int)

In [27]:
newdf['err_msg']=newdf['Log'].str.split().str.get(2)

In [28]:
newdf['err_r']=newdf['err_msg'].str.split('-').str.get(0)
newdf['err_m']=newdf['err_msg'].str.split('-').str.get(1)
newdf['err_n']=newdf['err_msg'].str.split('-').str.get(2)
newdf['err_cj']=newdf['err_msg'].str.split('-').str.get(3)
newdf['err_u']=newdf['err_msg'].str.split('-').str.get(4)

In [29]:
newdf=newdf.dropna()

In [30]:
newdf['err_r']=newdf['err_r'].str.replace('R','').astype(int)

In [31]:
newdf['err_m']=newdf['err_m'].str.replace('M','').astype(int)

In [32]:
newdf['err_n']=newdf['err_n'].str.replace('N','')
newdf['err_n']=newdf['err_n'].str.replace('A','10')
newdf['err_n']=newdf['err_n'].str.replace('B','11')
newdf['err_n']=newdf['err_n'].str.replace('C','12')
newdf['err_n']=newdf['err_n'].str.replace('D','13')
newdf['err_n']=newdf['err_n'].str.replace('E','14')
newdf['err_n']=newdf['err_n'].str.replace('F','15')
newdf['err_n']=newdf['err_n'].str.replace('L','2')

In [33]:
newdf['err_n']=newdf['err_n'].astype(int)

In [34]:
newdf['err_cj']=newdf['err_cj'].str.replace('C:J','')
newdf['err_cj']=newdf['err_cj'].str.replace('I:J','')
newdf['err_cj']=newdf['err_cj'].str.replace('U18','23')
newdf['err_cj']=newdf['err_cj'].str.replace('U','')

In [35]:
newdf['err_cj']=newdf['err_cj'].astype(int)

In [36]:
newdf['err_u']=newdf['err_u'].str.replace('U','')
newdf['err_u']=newdf['err_u'].str.replace('11','2')
newdf['err_u']=newdf['err_u'].str.replace('C','3')

In [37]:
newdf['err_u']=newdf['err_u'].astype(int)

In [38]:
newdf

,Log,Label,New,err_id,err_msg,err_r,err_m,err_n,err_cj,err_u
0,1117838570 2005.06.03 R02-M1-N0-C:J12-U11 200...,1,1,1117838570,R02-M1-N0-C:J12-U11,2,1,0,12,2
1,1117838570 2005.06.03 R02-M1-N0-C:J12-U11 200...,1,1,1117838570,R02-M1-N0-C:J12-U11,2,1,0,12,2
2,1117838570 2005.06.03 R02-M1-N0-C:J12-U11 200...,1,1,1117838570,R02-M1-N0-C:J12-U11,2,1,0,12,2
3,1117838570 2005.06.03 R02-M1-N0-C:J12-U11 200...,1,1,1117838570,R02-M1-N0-C:J12-U11,2,1,0,12,2
4,1117838570 2005.06.03 R02-M1-N0-C:J12-U11 200...,1,1,1117838570,R02-M1-N0-C:J12-U11,2,1,0,12,2
...,...,...,...,...,...,...,...,...,...,...
4152654,1118545530 2005.06.11 R30-M0-N9-C:J16-U01 2005...,0,0,1118545530,R30-M0-N9-C:J16-U01,30,0,9,16,1
4152655,1118545530 2005.06.11 R30-M0-N9-C:J16-U01 2005...,0,0,1118545530,R30-M0-N9-C:J16-U01,30,0,9,16,1
4152656,1118545530 2005.06.11 R30-M0-N9-C:J16-U01 2005...,0,0,1118545530,R30-M0-N9-C:J16-U01,30,0,9,16,1
4152657,1118545530 2005.06.11 R30-M0-N9-C:J16-U01 2005...,0,0,1118545530,R30-M0-N9-C:J16-U01,30,0,9,16,1
4152658,1118545530 2005.06.11 R30-M0-N9-C:J16-U01 2005...,0,0,1118545530,R30-M0-N9-C:J16-U01,30,0,9,16,1

In [39]:
newdf['Label'].value_counts()

1    3892561
0      69692
Name: Label, dtype: int64

In [40]:
from imblearn.over_sampling import SMOTE
# Resampling the minority class. The strategy can be changed as required.
sm = SMOTE(sampling_strategy='minority', random_state=42)
# Fit the model to generate the data.
oversampled_X, oversampled_Y = sm.fit_resample(newdf.drop(['err_id','Label','Log','err_msg'], axis=1), newdf['Label'])
oversampled = pd.concat([pd.DataFrame(oversampled_Y), pd.DataFrame(oversampled_X)], axis=1)

In [41]:
oversampled

         Label  New  err_r  err_m  err_n  err_cj  err_u
0            1    1      2      1      0      12      2
1            1    1      2      1      0      12      2
2            1    1      2      1      0      12      2
3            1    1      2      1      0      12      2
4            1    1      2      1      0      12      2
...        ...  ...    ...    ...    ...     ...    ...
7785117      0    0     30      0      9      16      1
7785118      0    0     30      0      9      16      1
7785119      0    0     30      0      9      16      1
7785120      0    0     30      0      9      16      1
7785121      0    0     30      0      9      16      1

[7785122 rows x 7 columns]

In [42]:
oversampled.corr()

           Label       New     err_r     err_m     err_n    err_cj     err_u
Label   1.000000  0.967653  0.005001  0.532639 -0.225965 -0.636262  0.560069
New     0.967653  1.000000 -0.017260  0.546915 -0.244389 -0.603306  0.573295
err_r   0.005001 -0.017260  1.000000 -0.117773  0.042112  0.010074 -0.027103
err_m   0.532639  0.546915 -0.117773  1.000000 -0.152858 -0.321144  0.322577
err_n  -0.225965 -0.244389  0.042112 -0.152858  1.000000  0.100066 -0.161104
err_cj -0.636262 -0.603306  0.010074 -0.321144  0.100066  1.000000 -0.351405
err_u   0.560069  0.573295 -0.027103  0.322577 -0.161104 -0.351405  1.000000

In [43]:
newdf.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 3962253 entries, 0 to 4152658
Data columns (total 10 columns):
 #   Column   Dtype
---  ------   -----
 0   Log      object
 1   Label    int64
 2   New      int64
 3   err_id   int64
 4   err_msg  object
 5   err_r    int64
 6   err_m    int64
 7   err_n    int64
 8   err_cj   int64
 9   err_u    int64
dtypes: int64(8), object(2)
memory usage: 332.5+ MB

In [44]:
test = pd.read_csv("/kaggle/input/convolve-epoch1/test.csv")
test

            ID                                                Log
0            0   1124336301 2005.08.17 R13-M1-N8-C:J12-U01 200...
1            1   1118553175 2005.06.11 R30-M0-N9-C:J16-U01 200...
2            2   1118536033 2005.06.11 R30-M0-N9-C:J16-U01 200...
3            3   1117992566 2005.06.05 R30-M1-N6-C:J03-U11 200...
4            4   1118538965 2005.06.11 R30-M0-N9-C:J16-U01 200...
...        ...                                                ...
595295  595295   1118768234 2005.06.14 R20-M0-NA-C:J17-U11 200...
595296  595296   1118370947 2005.06.09 R15-M0-NA-C:J02-U01 200...
595297  595297   1118540242 2005.06.11 R30-M0-N9-C:J16-U01 200...
595298  595298   1118538947 2005.06.11 R30-M0-N9-C:J16-U01 200...
595299  595299   1118165805 2005.06.07 R23-M1-N5-C:J16-U11 200...

[595300 rows x 2 columns]

In [45]:
test['err_id']=test[' Log'].str.split().str.get(0).astype(int)

In [46]:
test

            ID                                                Log      err_id
0            0   1124336301 2005.08.17 R13-M1-N8-C:J12-U01 200...  1124336301
1            1   1118553175 2005.06.11 R30-M0-N9-C:J16-U01 200...  1118553175
2            2   1118536033 2005.06.11 R30-M0-N9-C:J16-U01 200...  1118536033
3            3   1117992566 2005.06.05 R30-M1-N6-C:J03-U11 200...  1117992566
4            4   1118538965 2005.06.11 R30-M0-N9-C:J16-U01 200...  1118538965
...        ...                                                ...         ...
595295  595295   1118768234 2005.06.14 R20-M0-NA-C:J17-U11 200...  1118768234
595296  595296   1118370947 2005.06.09 R15-M0-NA-C:J02-U01 200...  1118370947
595297  595297   1118540242 2005.06.11 R30-M0-N9-C:J16-U01 200...  1118540242
595298  595298   1118538947 2005.06.11 R30-M0-N9-C:J16-U01 200...  1118538947
595299  595299   1118165805 2005.06.07 R23-M1-N5-C:J16-U11 200...  1118165805

[595300 rows x 3 columns]

In [47]:
test["c_or_i"] = test[" Log"].str.split().str[-1]

In [48]:
test=test.replace('interrupt','50')

In [49]:
test['New']=test.c_or_i.apply(lambda x: np.where(x.isdigit(),x,'1'))

In [50]:
test['New']=test['New'].astype(int)

In [51]:
test['New'][test['New'] > 51] = 1

/opt/conda/lib/python3.7/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

In [52]:
test['New'][test['New'] < 50] = 1

/opt/conda/lib/python3.7/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

In [53]:
test['New'][test['New'] == 50] = 0

/opt/conda/lib/python3.7/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

In [54]:
test=test.drop('c_or_i',axis='columns')

In [55]:
test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 595300 entries, 0 to 595299
Data columns (total 4 columns):
 #   Column  Non-Null Count   Dtype
---  ------  --------------   -----
 0   ID      595300 non-null  int64
 1    Log    595300 non-null  object
 2   err_id  595300 non-null  int64
 3   New     595300 non-null  int64
dtypes: int64(3), object(1)
memory usage: 18.2+ MB

In [56]:
test['err_msg']=test[' Log'].str.split().str.get(2)

In [57]:
test['err_r']=test['err_msg'].str.split('-').str.get(0)
test['err_m']=test['err_msg'].str.split('-').str.get(1)
test['err_n']=test['err_msg'].str.split('-').str.get(2)
test['err_cj']=test['err_msg'].str.split('-').str.get(3)
test['err_u']=test['err_msg'].str.split('-').str.get(4)

In [58]:
test['New'].value_counts()

1    379020
0    216280
Name: New, dtype: int64

In [59]:
test=test.fillna(0)

In [60]:
test['err_r']=test['err_r'].str.replace('R','')
test['err_r']=test['err_r'].str.replace('NULL','0')
test['err_r']=test['err_r'].str.replace('UNKNOWN_LOCATION','0')

In [61]:
test['err_r']=test['err_r'].astype(int)

In [62]:
test['err_m']=test['err_m'].str.replace('M','')

In [63]:
test=test.fillna(0)

In [64]:
test['err_m']=test['err_m'].astype(int)

In [65]:
test['err_n']=test['err_n'].str.replace('N','')
test['err_n']=test['err_n'].str.replace('A','10')
test['err_n']=test['err_n'].str.replace('B','11')
test['err_n']=test['err_n'].str.replace('C','12')
test['err_n']=test['err_n'].str.replace('D','13')
test['err_n']=test['err_n'].str.replace('E','14')
test['err_n']=test['err_n'].str.replace('F','15')
test['err_n']=test['err_n'].str.replace('L','2')

In [66]:
test=test.fillna(0)

In [67]:
test['err_n']=test['err_n'].astype(int)

In [68]:
test['err_cj']=test['err_cj'].str.replace('C:J','')
test['err_cj']=test['err_cj'].str.replace('I:J','')
test['err_cj']=test['err_cj'].str.replace('U18','23')
test['err_cj']=test['err_cj'].str.replace('U','')

In [69]:
test=test.fillna(0)

In [70]:
test['err_cj']=test['err_cj'].astype(int)

In [71]:
test['err_u']=test['err_u'].str.replace('U','')
test['err_u']=test['err_u'].str.replace('11','2')
test['err_u']=test['err_u'].str.replace('C','3')
test['err_u']=test['err_u'].str.replace('A','0')
test['err_u']=test['err_u'].str.replace('E','0')
test['err_u']=test['err_u'].str.replace('D','0')

In [72]:
test=test.fillna(0)

In [73]:
test['err_u']=test['err_u'].astype(int)

In [74]:
from sklearn.model_selection import train_test_split

In [75]:
x = oversampled.drop(['Label'],axis='columns')
# x = df_upsampled.drop(['Label','Log','err_msg'],axis='columns')
y = oversampled.Label

In [76]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.01,random_state=42,shuffle=True)

In [77]:
from sklearn.svm import SVC
model = SVC(C=10)

In [78]:
from sklearn.ensemble import RandomForestClassifier
rfc = RandomForestClassifier(n_estimators=100)

In [79]:
X_test=test.drop(['ID',' Log','err_msg','err_id'],axis='columns')

In [80]:
rfc.fit(x_train, y_train)

RandomForestClassifier()

Accuracy Score

In [86]:
rfc.score(x_test,y_test)

0.9844319991779273

F1 Score

In [84]:
from sklearn.metrics import f1_score
y_pred = rfc.predict(x_test)
f1_score(y_test, y_pred)

0.9843983317027961

In [85]:
from sklearn.tree import DecisionTreeClassifier
decision_tree = DecisionTreeClassifier()
decision_tree.fit(x_train, y_train)
predictions = decision_tree.predict(X_test)

Accuracy Score

In [88]:
decision_tree.score(x_test, y_test)

0.9844576889482608

F1 Score

In [87]:
from sklearn.metrics import f1_score
y_pred = decision_tree.predict(x_test)
f1_score(y_test, y_pred)

0.9844228739153943

In [89]:
from imblearn.ensemble import BalancedBaggingClassifier
from sklearn.tree import DecisionTreeClassifier
#Create an instance
classifier = BalancedBaggingClassifier(base_estimator=DecisionTreeClassifier(),
                                sampling_strategy='not majority',
                                replacement=False,
                                random_state=42)
classifier.fit(x_train, y_train)

BalancedBaggingClassifier(base_estimator=DecisionTreeClassifier(),
                          random_state=42, sampling_strategy='not majority')

Accuracy Score

In [91]:
classifier.score(x_test,y_test)

0.9844448440630941

F1 Score

In [92]:
from sklearn.metrics import f1_score
y_pred = decision_tree.predict(x_test)
f1_score(y_test, y_pred)

0.9844228739153943

In [93]:
predictions = decision_tree.predict(X_test)

In [94]:
predictions

array([1, 0, 0, ..., 0, 0, 1])

In [95]:
output = pd.DataFrame({'ID': test.ID, 'Label': predictions})

In [96]:
output

            ID  Label
0            0      1
1            1      0
2            2      0
3            3      1
4            4      0
...        ...    ...
595295  595295      1
595296  595296      1
595297  595297      0
595298  595298      0
595299  595299      1

[595300 rows x 2 columns]

In [97]:
output.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 595300 entries, 0 to 595299
Data columns (total 2 columns):
 #   Column  Non-Null Count   Dtype
---  ------  --------------   -----
 0   ID      595300 non-null  int64
 1   Label   595300 non-null  int64
dtypes: int64(2)
memory usage: 9.1 MB

In [98]:
output['Label']=output['Label'].astype(str)

In [99]:
output['Label']=output['Label'].str.replace('0','abnormal')
output['Label']=output['Label'].str.replace('1','normal')

In [100]:
output['Label'].value_counts()

normal      394729
abnormal    200571
Name: Label, dtype: int64

In [101]:
output.to_csv('file2.csv')